# Build by JDM-Buildozer
name: JDM_template
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APK
        uses: digreatbrian/buildozer-action@v1
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JDM_template-0.0.1
          path: ./bin/*.apk
